/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'git-util-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./git-util-native.android-arm64.node')
          } else {
            nativeBinding = require('git-util-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'git-util-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./git-util-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('git-util-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'git-util-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./git-util-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('./git-util-native.win32-x64-msvc.node')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'git-util-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./git-util-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('git-util-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'git-util-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./git-util-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('git-util-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'git-util-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./git-util-native.darwin-universal.node')
      } else {
        nativeBinding = require('git-util-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'git-util-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./git-util-native.darwin-x64.node')
          } else {
            nativeBinding = require('git-util-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'git-util-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./git-util-native.darwin-arm64.node')
          } else {
            nativeBinding = require('git-util-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'git-util-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./git-util-native.freebsd-x64.node')
      } else {
        nativeBinding = require('git-util-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'git-util-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./git-util-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('git-util-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'git-util-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./git-util-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('git-util-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'git-util-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./git-util-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('git-util-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'git-util-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./git-util-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('git-util-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'git-util-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./git-util-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('git-util-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'git-util-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./git-util-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('git-util-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'git-util-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./git-util-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('git-util-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'git-util-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./git-util-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('git-util-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'git-util-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./git-util-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('git-util-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { FileStatusType, hasGit, isGitRepository, getBranches, isCommited, isPushed, getCurrentBranch, getBranchInRemote, hasRemote, getRemote, getTags, getCommitLogFormat, getBranchAuthors, getAllAuthors, getBranchCreateInfo, getBranchsCreateInfo, getRepositoryInfoFull, getRepositoryInfoSimple, getContributeStat, getRepoFileList, getCommitFileStatus, getFileModifyStatBetweenCommit, getFilesStatusBetweenCommit, diffFileContext, getFileContent, getFileByHash, getDiffFileStatBetweenCommit, getFilesDiffContext, getCommitWithinBranches } = nativeBinding

module.exports.FileStatusType = FileStatusType
module.exports.hasGit = hasGit
module.exports.isGitRepository = isGitRepository
module.exports.getBranches = getBranches
module.exports.isCommited = isCommited
module.exports.isPushed = isPushed
module.exports.getCurrentBranch = getCurrentBranch
module.exports.getBranchInRemote = getBranchInRemote
module.exports.hasRemote = hasRemote
module.exports.getRemote = getRemote
module.exports.getTags = getTags
module.exports.getCommitLogFormat = getCommitLogFormat
module.exports.getBranchAuthors = getBranchAuthors
module.exports.getAllAuthors = getAllAuthors
module.exports.getBranchCreateInfo = getBranchCreateInfo
module.exports.getBranchsCreateInfo = getBranchsCreateInfo
module.exports.getRepositoryInfoFull = getRepositoryInfoFull
module.exports.getRepositoryInfoSimple = getRepositoryInfoSimple
module.exports.getContributeStat = getContributeStat
module.exports.getRepoFileList = getRepoFileList
module.exports.getCommitFileStatus = getCommitFileStatus
module.exports.getFileModifyStatBetweenCommit = getFileModifyStatBetweenCommit
module.exports.getFilesStatusBetweenCommit = getFilesStatusBetweenCommit
module.exports.diffFileContext = diffFileContext
module.exports.getFileContent = getFileContent
module.exports.getFileByHash = getFileByHash
module.exports.getDiffFileStatBetweenCommit = getDiffFileStatBetweenCommit
module.exports.getFilesDiffContext = getFilesDiffContext
module.exports.getCommitWithinBranches = getCommitWithinBranches
