/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

let nativeBinding = null

nativeBinding = require('./git-util-native.win32-x64-gnu.node')

const { FileStatusType, hasGit, isGitRepository, getBranches, isCommited, isPushed, getCurrentBranch, getBranchInRemote, hasRemote, getRemote, getTags, getCommitLogFormat, getBranchAuthors, getAllAuthors, getBranchCreateInfo, getBranchsCreateInfo, getRepositoryInfoFull, getRepositoryInfoSimple, getContributeStat, getRepoFileList, getCommitFileStatus, getFileModifyStatBetweenCommit, getFilesStatusBetweenCommit, diffFileContext, getFileContent, getFileByHash, getDiffFileStatBetweenCommit, getFilesDiffContext } = nativeBinding

module.exports.FileStatusType = FileStatusType
module.exports.hasGit = hasGit
module.exports.isGitRepository = isGitRepository
module.exports.getBranches = getBranches
module.exports.isCommited = isCommited
module.exports.isPushed = isPushed
module.exports.getCurrentBranch = getCurrentBranch
module.exports.getBranchInRemote = getBranchInRemote
module.exports.hasRemote = hasRemote
module.exports.getRemote = getRemote
module.exports.getTags = getTags
module.exports.getCommitLogFormat = getCommitLogFormat
module.exports.getBranchAuthors = getBranchAuthors
module.exports.getAllAuthors = getAllAuthors
module.exports.getBranchCreateInfo = getBranchCreateInfo
module.exports.getBranchsCreateInfo = getBranchsCreateInfo
module.exports.getRepositoryInfoFull = getRepositoryInfoFull
module.exports.getRepositoryInfoSimple = getRepositoryInfoSimple
module.exports.getContributeStat = getContributeStat
module.exports.getRepoFileList = getRepoFileList
module.exports.getCommitFileStatus = getCommitFileStatus
module.exports.getFileModifyStatBetweenCommit = getFileModifyStatBetweenCommit
module.exports.getFilesStatusBetweenCommit = getFilesStatusBetweenCommit
module.exports.diffFileContext = diffFileContext
module.exports.getFileContent = getFileContent
module.exports.getFileByHash = getFileByHash
module.exports.getDiffFileStatBetweenCommit = getDiffFileStatBetweenCommit
module.exports.getFilesDiffContext = getFilesDiffContext
