/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null

nativeBinding = require('./giter-native-win.win32-x64-gnu.node')
const { getIconFromPe } = nativeBinding

module.exports.getIconFromPe = getIconFromPe
