/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

let nativeBinding = null

nativeBinding = import('./giter-native-win.win32-x64-gnu.node')
const { getIconFromPe } = nativeBinding
export  { getIconFromPe }
